name: dsc_ur
description:  A practice app for the University of Redlands DSC Dev Team!
version: 1.1.1+5

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^0.1.3
  flutter_icons: ^1.1.0
  eva_icons_flutter: ^2.0.1
  # Styling
  dynamic_theme: ^1.0.1
  flare_flutter: ^2.0.6
  gradient_widgets: ^0.5.2
  liquid_swipe: ^1.5.0
  google_fonts: ^1.1.1
  # Functionality
  url_launcher: ^5.5.0
  cached_network_image: ^2.3.3
  carousel_slider: ^2.3.1
  # Firebase
  firebase_core: ^0.5.2  # Firebase Core Flutter SDK
  firebase_analytics: ^6.2.0  # FlutterFire plugin for Google Analytics
  firebase_auth: ^0.18.3 # Firebase Authentication
  cloud_firestore: ^0.14.3  # Cloud Firestore
  cloud_functions: ^0.7.0+1 # Cloud Functions
  firebase_crashlytics: ^0.2.3 # Firebase Crashlytics
  firebase_performance: ^0.4.2  # Firebase-App Performance Monitoring
  firebase_in_app_messaging: ^0.2.2 # Firebase in-app messaging


dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  flutter_spinkit: ^4.1.2+1

flutter_icons:
  android: 'launcher_icon'
  image_path_android: 'assets/icon/icon-legacy.png'
  adaptive_icon_foreground: 'assets/icon/icon-adaptive.png'
  adaptive_icon_background: '#fafafa'

  ios: true
  image_path_ios: 'assets/icon/icon-ios.png'

flutter:
  uses-material-design: true

  assets:
     - assets/credits/
     - assets/flare/
     - assets/icon/
     - assets/music/
     - assets/images/


  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik/Rubik-Italic.ttf
          style: italic

    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Medium.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Bold.ttf

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
